#!/usr/bin/env python3
"""Regenerate required-applets.txt from a shipped initramfs.

    tests/busybox/gen-required.py <unpacked-initramfs-dir> [-o FILE]

Derived from the real scripts rather than hand-written, so it cannot drift from what
Slax actually calls. Run it again if upstream ever ships a new initramfs.
"""
import argparse
import os
import re
import subprocess
import sys

# A word is "invoked" if it appears where a command can start.
COMMAND_POS = re.compile(
    r"(?:^|[;&|(`]|\$\(|\bthen\b|\bdo\b|\belse\b|\bif\b|\bwhile\b|\buntil\b)\s*"
    r"([a-zA-Z_][a-zA-Z0-9_.\-]*)", re.M)

SCRIPTS = ("init", "lib/livekitlib", "shutdown")

HEADER = """# Applets that /init, lib/livekitlib and /shutdown actually invoke.
#
# Generated by tests/busybox/gen-required.py from the SHIPPED initramfs, not hand-written.
# Method: words in command position (start of line, or after ; & | ( ` $( then do else
# if while until), intersected with the stock busybox's own --list. Comments are stripped
# first -- without that, "# last chance, try to modprobe..." contributes `last`, which is
# an applet and is never called. That one false positive is why the count was 54 on 2026-09-20 and
# not the 55 the original plan recorded.
#
# Gate 1 hard-fails if a candidate busybox is missing any of these.
"""


def required(tree: str) -> list:
    words = set()
    for rel in SCRIPTS:
        path = os.path.join(tree, rel)
        if not os.path.isfile(path):
            raise SystemExit(f"gen-required: {path} missing -- is {tree} an initramfs?")
        text = open(path, errors="ignore").read()
        text = re.sub(r"(?m)(?<!\$)#.*$", "", text)     # strip comments
        words |= set(COMMAND_POS.findall(text))

    bb = os.path.join(tree, "bin", "busybox")
    r = subprocess.run([bb, "--list"], capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f"gen-required: {bb} --list failed -- this host may lack IA32 "
                         f"support: {r.stderr.strip()[:200]}")
    return sorted(words & set(r.stdout.split()))


def main(argv: list) -> int:
    ap = argparse.ArgumentParser(prog="gen-required.py")
    ap.add_argument("tree", help="an unpacked initramfs directory")
    ap.add_argument("-o", "--output",
                    default=os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                         "required-applets.txt"))
    a = ap.parse_args(argv[1:])
    used = required(a.tree)
    with open(a.output, "w") as f:
        f.write(HEADER + "\n".join(used) + "\n")
    print(f"{len(used)} applets -> {a.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
