#!/usr/bin/env python3
"""kitchen sources -- what is in a built ISO, and where the source of each part lives.

    kitchen sources <iso> [--provenance FILE] [--json FILE] [--markdown FILE]
                          [--fetch DIR] [--allow-dirty] [--strict]

A published image carries the source of what its build compiled, built or modified, and
says where each upstream publishes the source of everything included unmodified. This
command works out which is which, for every file in the ISO, from evidence rather than
from a list someone keeps:

  slax       sha256 equals the committed stock manifest for the base image
             (docs/30-inventory/manifests/{bootfiles,isofiles,initramfs}-<target>.sha256)
  debian     a bundle a recorded bundle.packages step produced, byte for byte: its packages
  slackware  the same, for Slackware packages
  prebuilt   a recorded download, installed unmodified -- a tarball or a payload -- or
             bytes pack copied from the build host (the MBR)
  built      compiled or assembled here: GRUB's EFI image, a busybox with a verified build
             claim, a binary a bundle.script declares
  ours       written or generated by a recipe or by kitchen itself; a script's bundle
             lists beside it each file the script says it fetched (KITCHEN-FETCHED)
  unresolved anything else, and the command exits 1

The evidence is the image's provenance sidecar (<iso>.provenance.json, written by `kitchen
pack`). A file matches a recorded step only if its sha256 is the one recorded, so a bundle
altered after the build is unresolved rather than silently attributed. A repacked
initramfs is opened and its members compared with the stock manifest one by one, because
"the parts that match Slax are Slax" is a claim, and a claim has to be counted.

WHAT WEAKENS A POINTER IS SAID. A download with no upstream_source, and a download the
recipe pinned no sha256 for (what it fetched is what that server served that day), are
warnings here and unresolved under --strict.

OFFLINE unless --fetch. With --fetch DIR it gathers the source of everything classed
`built`, plus the project tree at the recorded commit WITH its submodules (GitHub's
automatic source archives leave submodules out). Unmodified upstream parts are pointed
at, not fetched.
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import lzma
import os
import re
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
import urllib.parse
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import need  # noqa: E402
import provenance  # noqa: E402

SCHEMA = "slax-kitchen/sources/v1"
CLASSES = ("slax", "debian", "slackware", "prebuilt", "built", "ours", "unresolved")
SLAX_SOURCE = "https://github.com/Tomas-M/linux-live"


# ------------------------------------------------------------------ pointers ------

def snapshot_url(source: str, version: str) -> str:
    """Debian's permanent archive page for one source package version. Epochs contain a
    colon, which the path has to carry encoded."""
    return ("https://snapshot.debian.org/package/"
            f"{urllib.parse.quote(source, safe='')}/{urllib.parse.quote(version, safe='')}/")


def launchpad_url(source: str, version: str) -> str:
    return (f"https://launchpad.net/ubuntu/+source/{urllib.parse.quote(source, safe='')}/"
            f"{urllib.parse.quote(version, safe='')}")


def host_source_url(pkg: dict | None, builder: dict | None) -> str | None:
    """Where the source of a BUILD-HOST package lives: Launchpad on Ubuntu, snapshot on
    Debian. None when the host package is unknown."""
    if not pkg or not pkg.get("source"):
        return None
    ver = pkg.get("source_version") or pkg.get("version")
    if (builder or {}).get("id") == "ubuntu":
        return launchpad_url(pkg["source"], ver)
    return snapshot_url(pkg["source"], ver)


# ------------------------------------------------------------------ inputs --------

def read_manifest(path: str) -> dict:
    """`sha256  ./path` lines -> {path: sha256}."""
    out = {}
    if os.path.isfile(path):
        for ln in open(path):
            parts = ln.rstrip("\n").split("  ", 1)
            if len(parts) == 2:
                out[parts[1][2:] if parts[1].startswith("./") else parts[1]] = parts[0]
    return out


def base_target(prov: dict, sources_yaml: dict) -> tuple[str | None, dict]:
    want = (prov.get("base") or {}).get("sha256")
    for name, t in (sources_yaml.get("targets") or {}).items():
        if want and t.get("sha256") == want:
            return name, t
    return None, {}


def stock_index(target: str | None, manifests: str) -> dict:
    """{path in the ISO: sha256} for the stock image, plus its initramfs members."""
    if not target:
        return {"files": {}, "initramfs": {}}
    files = {f"slax/boot/{p}": h for p, h in
             read_manifest(os.path.join(manifests, f"bootfiles-{target}.sha256")).items()}
    files.update(read_manifest(os.path.join(manifests, f"isofiles-{target}.sha256")))
    return {"files": files,
            "initramfs": read_manifest(os.path.join(manifests, f"initramfs-{target}.sha256"))}


def iso_files(iso: str) -> dict:
    """{path: sha256} for every regular file in the ISO, hashed from its extent."""
    import diff
    ents = diff._entries(iso)
    out = {}
    with open(iso, "rb") as fh:
        for path, e in ents.items():
            if e["type"] != "file" or e["lba"] is None:
                continue
            out[path.lstrip("/")] = diff._sha256_extent(fh, e["lba"], e["size"])
            if path == "/slax/boot/isolinux.bin":
                out["slax/boot/isolinux.bin@64"] = diff._sha256_extent(
                    fh, e["lba"], e["size"], diff.BIT_LEN)
    return out


def cpio_members(blob: bytes) -> dict:
    """{path: sha256} for the regular files in a `newc` cpio archive.

    Parsed here rather than shelled out to cpio, because unpacking needs privilege to get
    the answer right: Slax's initramfs holds seven device nodes, and a non-root cpio
    writes them as empty regular files (docs/30-inventory/manifests/README.md), which
    would then read as seven members the stock manifest does not have. Reading the headers
    costs nothing and answers for any user.
    """
    def field(at: int, i: int) -> int:
        """Header field `i`: newc writes each as eight ASCII hex digits, after the magic.

        STRICTLY eight hex digits. int() accepts a sign and surrounding space, so a field
        written `-000006e` parsed as a negative length, the next offset landed back on the
        current one, and the loop never ended -- on an image the operator did not build."""
        raw = blob[at + 6 + i * 8: at + 14 + i * 8]
        if not HEX8.fullmatch(raw):
            raise ValueError(f"cpio: header field {i} at {at} is not eight hex digits")
        return int(raw, 16)

    # Stops at the first TRAILER!!!, so a concatenated initramfs (several archives one
    # after another, which the kernel accepts) reads as its first segment. Slax builds one.
    out: dict[str, str] = {}
    linked: dict[tuple, list[str]] = {}       # inode -> the names sharing it
    content: dict[tuple, str] = {}            # inode -> the hash of the one copy of its data
    off, trailer = 0, False
    while off + 110 <= len(blob):
        if blob[off:off + 6] != b"070701":
            break
        mode, nlink, filesize = field(off, 1), field(off, 4), field(off, 6)
        namesize = field(off, 11)
        name_at = off + 110
        data_at = (name_at + namesize + 3) & ~3
        if namesize < 1 or data_at + filesize > len(blob):
            raise ValueError("cpio: the archive ends in the middle of a member")
        name = blob[name_at: name_at + namesize - 1].decode("utf-8", "replace")
        if name == "TRAILER!!!":
            trailer = True
            break
        if stat.S_ISREG(mode):
            digest = hashlib.sha256(blob[data_at:data_at + filesize]).hexdigest()
            out[name] = digest
            # HARD LINKS. newc stores the data once, with the LAST name; every earlier
            # name gets filesize 0, which would hash as the empty file and read as a
            # member that no longer matches Slax. Names sharing an inode share the hash.
            if nlink > 1:
                ino = (field(off, 0), field(off, 7), field(off, 8))
                linked.setdefault(ino, []).append(name)
                if filesize:
                    content[ino] = digest
        off = (data_at + filesize + 3) & ~3
    if not trailer:
        # Every newc archive ends with one. Running off the end without seeing it means
        # the tail was cut off, and the members read so far are not the whole story.
        raise ValueError("cpio: no TRAILER!!! -- the archive is truncated")
    for ino, names in linked.items():
        if ino in content:
            for n in names:
                out[n] = content[ino]
    return out


# Slax's initramfs unpacks to about 40 MiB. The cap is for an image from somewhere else:
# xz compresses zeroes about 1000:1, so a 20 MiB initrfs.img can ask for 20 GiB, and
# `kitchen sources` would be killed by the OOM killer rather than say what it found.
INITRAMFS_MAX = 512 << 20


def initramfs_from_bytes(blob: bytes) -> dict | None:
    """{member: sha256} for an xz-compressed newc initramfs, or None when the bytes are
    not one. Malformed input is an answer, not a traceback: this runs on images from
    elsewhere, and `kitchen sources` says what it could not read rather than dying."""
    try:
        d = lzma.LZMADecompressor()
        raw = d.decompress(blob, max_length=INITRAMFS_MAX)
        if not d.eof:
            return None                     # more than the cap, or a truncated stream
        return cpio_members(raw) or None
    except (lzma.LZMAError, ValueError, EOFError, MemoryError):
        return None


def initramfs_members(iso: str) -> dict | None:
    """{member path: sha256} for the initramfs inside an ISO, or None if it cannot be read.

    The stock manifests record every regular file in the initramfs
    (docs/30-inventory/manifests/initramfs-<target>.sha256), and the only way to say which
    of an image's members are still Slax's is to look at them.
    """
    import diff
    e = diff._entries(iso).get("/slax/boot/initrfs.img")
    if not e or e.get("lba") is None:
        return None
    with open(iso, "rb") as fh:
        fh.seek(e["lba"] * diff.SECTOR)
        blob = fh.read(e["size"])
    return initramfs_from_bytes(blob)


def initramfs_delta(members: dict | None, stock: dict) -> dict:
    """Which of an initramfs's members are the stock image's, member by member.

    Pure. `members` is None when the initramfs could not be unpacked, and then nothing is
    claimed about it -- the point of this is to stop asserting that the parts that match
    Slax match Slax."""
    # The manifest first: with nothing to compare against, that is the reason whether or
    # not the image's initramfs could be read, and saying "could not be read" about an
    # image that read perfectly sends the reader after the wrong problem.
    if not stock:
        return {"compared": False,
                "why": "this target has no committed initramfs manifest to compare against"}
    if members is None:
        return {"compared": False, "why": "the initramfs in the image could not be read"}
    same = [p for p, h in members.items() if stock.get(p) == h]
    return {"compared": True, "members": len(members), "stock_members": len(same),
            "changed": sorted(p for p, h in members.items() if stock.get(p) != h),
            "removed": sorted(p for p in stock if p not in members)}


def alpine_aports_url(release: str | None, name: str) -> str | None:
    """Alpine's recipe for a package -- APKBUILD, patches, the upstream tarball it names --
    on the stable branch of the build container's release. A branch, not the release tag:
    `apk add` installs the branch's newest build, which can be newer than the tag (musl was
    1.2.4_git20230717-r6 on 3.19-stable while the v3.19.9 tag had -r5). The recorded version
    says which build it was."""
    m = re.match(r"^(\d+\.\d+)\.", release or "")
    return (f"https://gitlab.alpinelinux.org/alpine/aports/-/tree/{m.group(1)}-stable/main/{name}"
            if m else None)


# ------------------------------------------------------------------ classify ------

def _pointer_for_prebuilt(step: dict) -> dict:
    """What a downloaded file points at. `pinned` is False when the recipe named no sha256,
    so the file is whatever that server served on build day: recorded, but not reproducible.
    Steps written before the verbs recorded it say nothing, and nothing is claimed for them."""
    return {"source": step.get("source"), "source_sha256": step.get("source_sha256"),
            "member": step.get("member"), "upstream_source": step.get("upstream_source"),
            "pinned": step.get("pinned")}


def _debian_pointer(rec: dict) -> dict:
    """A package record with its source package and snapshot URL filled in. Debian omits
    Source: when the source package has the binary's name and version, so that is the
    fallback; with no version at all there is no pointer, and the caller says so."""
    src = rec.get("source") or rec.get("package")
    ver = rec.get("source_version") or rec.get("version")
    return dict(rec, source=src, source_version=ver,
                source_published_at=snapshot_url(src, ver) if src and ver else None)


def from_debian(origin: str) -> bool:
    """True when an apt index filename names an archive Debian itself runs.

    The origin is a FILENAME: the archive URI with "/" turned into "_", so everything
    before the first "_" is the host and the rest is the path. `debian.org` can sit
    anywhere in that path -- `mirror.example.com_debian.org_pub_dists_...` -- so only the
    host is tested, and a package from someone else's mirror stays undeclared."""
    host = (origin or "").split("_", 1)[0].split(":", 1)[0]
    # Any debian.org host counts, `people.debian.org` included, so a personal repository
    # there is taken for an archive Debian runs. It is still Debian's infrastructure and
    # the alternative is a hand-kept list of archive hostnames; the recipe declaring the
    # repository is what makes the pointer right, and this is the fallback.
    return host == "debian.org" or host.endswith(".debian.org")
APT_QUOTED = set('\\|{}[]<>"^~_=!@#$%^&*')


def apt_list_prefix(uri: str) -> str:
    """The name apt gives an archive's index files (apt-pkg's URItoFileName): the URI with
    no scheme or credentials, the characters apt quotes written as %xx, and "/" made "_".
    http://deb.debian.org/debian/ -> deb.debian.org_debian"""
    u = urllib.parse.urlsplit(uri)
    s = (u.hostname or "") + (f":{u.port}" if u.port else "") + u.path.rstrip("/")
    s = "".join(f"%{ord(c):02x}" if c in APT_QUOTED or ord(c) <= 0x20 or ord(c) >= 0x7f else c
                for c in s)
    return s.replace("/", "_")


def _packages(step: dict, flavour: str) -> tuple[list[dict], list[str], list[str]]:
    """Every package a bundle.packages/bundle.script step put in its bundle, where its source
    is published, what prevents saying so (problems) and what weakens it (warnings).

    Changed or new stanzas from the status diff, plus reinstalled ones known only from their
    .debs. Which archive a package came from is the apt index its .deb's sha256 was found in,
    recorded by the verb: a package from a recipe's own repository points at that
    repository's upstream_source, not at snapshot.debian.org, which never had it.
    """
    script = step.get("verb") == "bundle.script"
    declared = [(apt_list_prefix(src["uri"]) + "_", src)
                for src in step.get("apt_sources") or [] if src.get("uri")]
    debs: dict = {}
    for d in step.get("debs") or []:
        if d.get("package"):
            debs.setdefault((d["package"], d.get("version"), d.get("architecture")), d)
            debs.setdefault((d["package"], d.get("version")), d)
    problems: list[str] = []
    warns: list[str] = []

    def pointed(rec: dict) -> dict:
        name = rec.get("package")
        deb = debs.get((name, rec.get("version"), rec.get("architecture"))) or \
            debs.get((name, rec.get("version"))) or {}
        origin = rec.get("origin") or deb.get("origin")
        repo = next((src for prefix, src in declared if origin and origin.startswith(prefix)), None)
        if repo is not None or (script and origin and not from_debian(origin)):
            up = (repo or step).get("upstream_source")
            where = f"the `{repo.get('name')}` repository" if repo else f"`{origin}`"
            if not up:
                warns.append(f"{name} came from {where}, which the recipe gives no upstream_source")
            return dict(rec, archive=(repo or {}).get("name") or origin, source_published_at=up)
        if origin and not from_debian(origin):
            problems.append(f"{name} came from an archive this step does not declare ({origin})")
            return dict(rec, archive=origin, source_published_at=None)
        if not origin and declared:
            problems.append(f"{name}: no record of which archive it came from, and this step "
                            "adds repositories")
            return dict(rec, source_published_at=None)
        out = dict(_debian_pointer(rec), archive="debian")
        if not out["source_published_at"]:
            problems.append(f"no source version recorded for {name}")
        return out

    seen, out = set(), []
    for i in step.get("installed") or []:
        key = (i.get("package"), i.get("version"))
        if key not in seen:
            seen.add(key)
            out.append(pointed(i))
    for d in step.get("debs") or []:
        key = (d.get("package"), d.get("version"))
        if d.get("package") and key not in seen:
            seen.add(key)
            out.append(pointed({k: d.get(k) for k in (
                "package", "version", "architecture", "source", "source_version", "origin")
                if d.get(k) is not None}))
    if flavour == "slackware":
        # Slackware has no Source field: a release publishes its source beside its packages,
        # and the recipe that installed them names that tree.
        up = step.get("upstream_source")
        names = step.get("slackware_installed") or []
        if names and not up:
            warns.append(f"{len(names)} Slackware package(s) ({', '.join(names[:3])}), and the "
                         "recipe gives no upstream_source for their release's source tree")
        for name in names:
            out.append({"package": name, "archive": "slackware", "source_published_at": up})
    return out, problems, warns


def classify(files: dict, stock: dict, prov: dict, target: str | None, target_info: dict,
             allow_dirty: bool = False, strict: bool = False,
             initramfs: dict | None = None) -> dict:
    """Pure: files {path: sha256} + stock index + provenance -> the sources document.

    `initramfs` is {member: sha256} for the image's own initramfs, or None when it could
    not be unpacked; initramfs_members() reads it from the ISO."""
    components, unresolved, warnings = [], [], []
    builder = prov.get("builder") or {}

    outputs: dict[str, list] = {}
    artifacts: dict[str, list] = {}
    # Which recipe (by position) last recorded a path's sha256, and which last wrote it at
    # all. A step that records its output also lists it as an artifact, so a tie means the
    # recording step was the last writer and the bytes must match what it recorded.
    last_output: dict[str, int] = {}
    last_artifact: dict[str, int] = {}
    recipes = prov.get("recipes") or []
    for i, r in enumerate(recipes):
        for s in r.get("steps") or []:
            if s.get("output"):
                outputs.setdefault(s["output"], []).append((r.get("recipe"), s))
                last_output[s["output"]] = i
        for a in r.get("artifacts") or []:
            if not a.startswith("-"):
                artifacts.setdefault(a.lstrip("/"), []).append(r.get("recipe"))
                last_artifact[a.lstrip("/")] = i
    generated = {g["path"]: g["sha256"] for g in (prov.get("pack") or {}).get("generated") or []}
    # The stock index the other way round. `bundle.renumber` renames a stock bundle without
    # touching a byte, so a path-keyed lookup misses it and the file falls through to the
    # recipe's artifact list -- Slax's own binary, reported as something this project wrote.
    stock_by_sha: dict = {}
    for sp, sh in stock["files"].items():
        if not sp.endswith("@64"):
            stock_by_sha.setdefault(sh, sp)

    def add(path, sha, cls, by=None, **detail):
        components.append({"path": path, "sha256": sha, "class": cls, "by": by,
                           **{k: v for k, v in detail.items() if v is not None}})

    def unresolve(path, reason):
        unresolved.append({"path": path, "reason": reason})

    for path in sorted(files):
        if path.endswith("@64"):
            continue
        sha = files[path]
        if stock["files"].get(path) == sha:
            add(path, sha, "slax")
            continue
        tail = path + "@64"
        if tail in files and stock["files"].get(tail) == files[tail]:
            add(path, sha, "slax", note="from byte 64 on it is the stock file, byte for "
                "byte; the mastering tool rewrites the boot-info table at bytes 8-63 and "
                "the first 64 bytes are skipped whole, so bytes 0-7 are not compared")
            continue
        recorded = [(rn, s) for rn, s in outputs.get(path, []) if s.get("output_sha256") == sha]
        if recorded:
            rn, s = recorded[-1]
            verb = s.get("verb")
            if path == "slax/boot/initrfs.img":
                parts = []
                for r2, s2 in outputs.get(path, []):
                    if s2.get("verb") == "initramfs.busybox":
                        claim = s2.get("claim") or {}
                        if not claim.get("verified"):
                            unresolve(f"{path}:bin/busybox",
                                      f"{r2}: busybox has no verified build claim "
                                      f"({'claim sha256 does not match the binary' if claim else 'no claim'})")
                            continue
                        c = claim.get("claim") or {}
                        release = (c.get("container") or {}).get("alpine_release")
                        linked = [dict(lib, source_published_at=alpine_aports_url(release, lib["name"]))
                                  for lib in c.get("linked") or []]
                        parts.append({"member": "bin/busybox", "class": "built", "by": r2,
                                      "linked": linked or None,
                                      "sources": c.get("sources"), "config": c.get("config"),
                                      "location": s2.get("source_location"),
                                      "container": (c.get("container") or {}).get("image")})
                    else:
                        parts.append({"class": "ours", "by": r2, "verb": s2.get("verb")})
                delta = initramfs_delta(initramfs, stock["initramfs"])
                if delta["compared"]:
                    note = (f"initramfs repacked by recipes: {delta['stock_members']} of "
                            f"{delta['members']} members are the stock image's, byte for byte")
                    if delta["changed"]:
                        note += f"; changed or added: {', '.join(delta['changed'][:8])}"
                        if len(delta["changed"]) > 8:
                            note += f", and {len(delta['changed']) - 8} more"
                    if delta["removed"]:
                        note += f"; removed: {len(delta['removed'])}"
                else:
                    note = ("initramfs repacked by recipes; its members were not compared: "
                            + delta["why"])
                add(path, sha, "ours", by=rn, note=note, parts=parts, stock_members=delta)
                continue
            if verb == "bundle.packages":
                flavour = s.get("flavour") or "debian"
                pk, problems, warns = _packages(s, flavour)
                if problems or (strict and warns):
                    unresolve(path, f"{rn}: " + "; ".join((problems + warns)[:5]))
                    continue
                warnings.extend(f"{rn}: {w}" for w in warns)
                add(path, sha, "slackware" if flavour == "slackware" else "debian", by=rn,
                    packages=pk, reinstall=s.get("reinstall"), apt_sources=s.get("apt_sources"))
            elif verb in ("bundle.fromTarball", "boot.payload"):
                ptr = _pointer_for_prebuilt(s)
                soft = []
                if not ptr["upstream_source"]:
                    soft.append(f"{verb} names no upstream_source for {ptr['source']}")
                if ptr["pinned"] is False:
                    soft.append(f"{verb} took {ptr['source']} with no sha256 pinned, so what "
                                "it fetched is what that server served, not a known file")
                if soft:
                    if strict:
                        unresolve(path, f"{rn}: " + "; ".join(soft))
                        continue
                    warnings.extend(f"{rn}: {m}" for m in soft)
                add(path, sha, "prebuilt", by=rn, **ptr)
            elif verb == "boot.uefi":
                tools = s.get("tools") or {}
                grub = tools.get("grub-efi-amd64-bin")
                if not grub:
                    unresolve(path, f"{rn}: boot.uefi recorded no GRUB package from the build host")
                    continue
                # host_package() returns just {"package": name} when dpkg-query -W fails, and
                # that dict is truthy: without this the component was `built` with a null
                # source, a null version and a null URL, and --fetch then crashed on it.
                if not (grub.get("source") and (grub.get("source_version") or grub.get("version"))):
                    unresolve(path, f"{rn}: the build host's {grub.get('package', 'GRUB')} "
                                    f"recorded no source version, so there is nothing to point at")
                    continue
                add(path, sha, "built", by=rn, what="GRUB EFI image (grub-mkstandalone)",
                    bootx64_sha256=s.get("bootx64_sha256"), grub_modules=s.get("grub_modules"),
                    host_packages=tools,
                    source_package={"source": grub.get("source"),
                                    "version": grub.get("source_version"),
                                    "published_at": host_source_url(grub, builder)})
            elif verb == "bundle.script":
                declared = {d["path"]: d for d in s.get("declares") or []}
                bad = [e for e in s.get("unowned_elf") or [] if e["path"] not in declared]
                if bad:
                    unresolve(path, f"{rn}: bundle.script left ELF files no package vouches "
                                    f"for and no `declares:` entry names: "
                                    + ", ".join(f"{e['path']} ({e.get('why', 'unowned')})"
                                                for e in bad[:5]))
                    continue
                if s.get("fetched") and not s.get("upstream_source"):
                    msg = f"{rn}: bundle.script fetched files but names no upstream_source"
                    if strict:
                        unresolve(path, msg)
                        continue
                    warnings.append(msg)
                pk, problems, warns = _packages(
                    s, "slackware" if s.get("slackware_installed") else "debian")
                if problems or (strict and warns):
                    unresolve(path, f"{rn}: " + "; ".join((problems + warns)[:5]))
                    continue
                warnings.extend(f"{rn}: {w}" for w in warns)
                # `network: true` is recorded and was not read anywhere. It does not make the
                # bundle unresolved -- fetched files, packages and declared binaries all
                # account for themselves -- but the record should say that this bundle's
                # account rests on what the script reported, because nothing here can see
                # a download the script made without the KITCHEN-FETCHED protocol.
                add(path, sha, "ours", by=rn, network=s.get("network"),
                    note="written by a script; what it fetched and installed is listed "
                    "separately" + (", and it ran with network access, so that list is the "
                                    "script's own account" if s.get("network") else ""),
                    fetched=[dict(f, upstream_source=s.get("upstream_source"))
                             for f in s.get("fetched") or []] or None,
                    packages=pk or None,
                    # A declared binary was COMPILED here: a built part, whose declared
                    # source --fetch gathers like any other.
                    parts=[{"member": d["path"], "class": "built", "by": rn,
                            "sources": [{"url": d["source_url"], "sha256": d["source_sha256"],
                                         "license": d.get("license")}]}
                           for d in declared.values()] or None)
            else:
                add(path, sha, "ours", by=rn, verb=verb)
            continue
        if generated.get(path) == sha:
            add(path, sha, "ours", by="kitchen pack", note="generated at pack time")
            continue
        if sha in stock_by_sha:
            add(path, sha, "slax", note=f"byte-identical to `{stock_by_sha[sha]}` in the stock "
                                        "image, under a different name -- bundle.renumber "
                                        "moves a bundle without rebuilding it")
            continue
        if path in last_output and last_artifact.get(path, -1) <= last_output[path]:
            rn, s = outputs[path][-1]
            unresolve(path, f"{rn}: {s.get('verb')} recorded sha256 {str(s.get('output_sha256'))[:12]}, "
                            f"the image has {sha[:12]}: changed after the step ran")
            continue
        if path in artifacts:
            add(path, sha, "ours", by=artifacts[path][-1], note="written or edited by a recipe")
            continue
        if path in stock["files"]:
            unresolve(path, "differs from the stock image, and no recorded step explains it")
        else:
            unresolve(path, "not in the stock image, and no recorded step produced it")

    # What a recipe copied in -- its own file included, since inline content lives there --
    # is `ours` only if the source archive holds it. main() compares each input with the
    # recorded commit before this runs.
    commits = {"kitchen": (prov.get("kitchen") or {}).get("commit"),
               "project": (prov.get("project") or {}).get("commit")}
    host_inputs = []
    for r in recipes:
        where = f"(recipe {r.get('recipe')})"
        inputs = [("the recipe file", r["recipe_file"])] if r.get("recipe_file") else []
        inputs += [(f"a {st.get('verb')} input", li) for st in r.get("steps") or []
                   for li in st.get("local_inputs") or []]
        for what, li in inputs:
            name = li.get("path") or li.get("outside")
            if li.get("outside"):
                hp = li.get("host_package")
                if hp and li.get("kind") == "file":
                    host_inputs.append({"recipe": r.get("recipe"), "input": name,
                                        "host_package": hp,
                                        "published_at": host_source_url(hp, builder)})
                else:
                    unresolve(where, f"{what}, `{name}`, is outside the kitchen and project "
                                     "checkouts and no build-host package owns it, so nothing "
                                     "says where its source is")
                continue
            if li.get("in_archive") is False and not allow_dirty:
                unresolve(where, f"{what}, `{name}`, is not what {li.get('root')} commit "
                                 f"{str(commits.get(li.get('root')))[:12]} holds "
                                 f"({li.get('why') or 'uncommitted, untracked or changed'})")
            if li.get("elf"):
                unresolve(where, f"{what}, `{name}`, copies compiled code "
                                 f"({', '.join(li['elf'][:3])}) whose source nothing records")

    mbr = (prov.get("pack") or {}).get("mbr")
    if mbr:
        add("(system area)", mbr.get("sha256"), "prebuilt", by="kitchen pack",
            what=f"isohybrid MBR, {mbr.get('file')} copied from the build host",
            host_package=mbr.get("package"),
            upstream_source=host_source_url(mbr.get("package"), builder))

    if not target:
        unresolve("(base image)", "the base ISO's sha256 is not a target in compat/sources.yaml")
    kitchen = prov.get("kitchen") or {}
    if not kitchen.get("commit"):
        unresolve("(kitchen)", "provenance records no kitchen commit")
    elif kitchen.get("dirty") and not allow_dirty:
        unresolve("(kitchen)", f"the kitchen tree was dirty when this image was built "
                               f"({kitchen.get('describe')}); its source cannot be a commit")

    not_redistributable = [{"recipe": r.get("recipe"), "why": (r.get("redistribution") or {}).get("why")}
                           for r in recipes if (r.get("redistribution") or {}).get("allowed") is False]

    firmware = firmware_facts(files, stock, recipes, target)
    if firmware["stock_bundle"] and not firmware["license_texts"]:
        warnings.append(f"{STOCK_FIRMWARE}: Slax's own build removed the license texts of the "
                        f"firmware in this bundle ({firmware_dir(target)}ipw2x00.LICENSE "
                        "remains); "
                        "the firmware-refresh recipe reinstalls Debian's, and remove-bundle "
                        "with drop: 01-firmware leaves the firmware out")

    summary = {c: 0 for c in CLASSES}
    for c in components:
        summary[c["class"]] += 1
    summary["unresolved"] = len(unresolved)
    iso = (prov.get("pack") or {}).get("iso") or {}
    return {
        "schema": SCHEMA,
        "image": iso,
        "base": {"target": target, "name": (prov.get("base") or {}).get("name"),
                 "sha256": (prov.get("base") or {}).get("sha256"),
                 "source_published_at": [SLAX_SOURCE]},
        "kitchen": {k: kitchen.get(k) for k in ("commit", "describe", "dirty")},
        "builder": builder,
        "summary": summary,
        "components": components,
        "unresolved": unresolved,
        "warnings": warnings,
        "not_redistributable": not_redistributable,
        "firmware": firmware,
        "host_inputs": host_inputs,
    }


HEX8 = re.compile(rb"[0-9A-Fa-f]{8}")
STOCK_FIRMWARE = "slax/modules/01-firmware.sb"
LICENSE_NAME = re.compile(r"(^|/)(LICENSES/|LICEN[CS]E)")


def firmware_dir(target: str | None) -> str:
    """Where firmware sits in an image of this target. Debian 12 is usr-merged and Slax's
    Debian bundles record usr/lib/firmware; Slackware is not merged and its bundles hold
    lib/firmware. Measured in all four stock 01-firmware.sb bundles."""
    return "lib/firmware/" if (target or "").startswith("slackware") else "usr/lib/firmware/"


def firmware_facts(files: dict, stock: dict, recipes: list, target: str | None = None) -> dict:
    """Which firmware the image carries and where its license texts are, from evidence.

    Slax's build deleted /usr/share/doc from its firmware packages, so the stock firmware
    bundle has no license texts beyond ipw2x00.LICENSE. A recorded bundle.packages step that
    reinstalled firmware packages put Debian's copyright files back; a script that fetched
    firmware records the license files it fetched beside it.
    """
    stock_bundle = STOCK_FIRMWARE in files and stock["files"].get(STOCK_FIRMWARE) == files[STOCK_FIRMWARE]
    license_texts, fetched_firmware, fetched_licenses, whence = [], 0, 0, False
    for r in recipes:
        for st in r.get("steps") or []:
            names = [d.get("package") for d in st.get("debs") or []] + \
                    [i.get("package") for i in st.get("installed") or []]
            fw = sorted({n for n in names if n and n.startswith("firmware-")})
            if st.get("verb") == "bundle.packages" and st.get("reinstall") and fw:
                license_texts.append({"recipe": r.get("recipe"), "bundle": st.get("output"),
                                      "packages": fw})
            for f in st.get("fetched") or []:
                # Both spellings, so a Slackware recipe's fetched firmware is counted too.
                path = str(f.get("path", ""))
                pre = next((d for d in ("usr/lib/firmware/", "lib/firmware/")
                            if path.startswith(d)), None)
                if not pre:
                    continue
                rel = path[len(pre):]
                if rel == "WHENCE":
                    whence = True
                elif LICENSE_NAME.search(rel):
                    fetched_licenses += 1
                else:
                    fetched_firmware += 1
    return {"stock_bundle": stock_bundle, "license_texts": license_texts,
            "fetched_firmware": fetched_firmware, "fetched_license_files": fetched_licenses,
            "fetched_whence": whence, "firmware_dir": firmware_dir(target)}


# ------------------------------------------------------------------ render --------

def markdown(doc: dict) -> str:
    img = doc.get("image") or {}
    base = doc.get("base") or {}
    s = doc["summary"]
    lines = [
        f"# Sources: `{img.get('name')}`",
        "",
        f"sha256 `{img.get('sha256')}`. Built from Slax `{base.get('target')}` "
        f"(`{base.get('name')}`, sha256 `{base.get('sha256')}`) with slax-kitchen "
        f"`{(doc.get('kitchen') or {}).get('describe')}`.",
        "",
    ]
    fw = doc.get("firmware") or {}
    if fw.get("stock_bundle") or fw.get("license_texts") or fw.get("fetched_firmware"):
        lines += ["Using an image that contains firmware implies acceptance of each firmware's "
                  "license terms.", ""]
        for lt in fw.get("license_texts") or []:
            lines += [f"- Debian's copyright files for {len(lt['packages'])} firmware packages are "
                      f"in `{lt['bundle']}`, reinstalled by `{lt['recipe']}`."]
        if fw.get("fetched_firmware"):
            lines += [f"- {fw['fetched_firmware']} firmware files were copied from linux-firmware, "
                      f"with {fw.get('fetched_license_files', 0)} license files"
                      + (" and WHENCE" if fw.get("fetched_whence") else "") + " beside them."]
        d = fw.get("firmware_dir") or "usr/lib/firmware/"
        if fw.get("stock_bundle") and not fw.get("license_texts"):
            lines += [f"- `{STOCK_FIRMWARE}` is Slax's firmware bundle, whose license texts Slax's "
                      f"own build removed (`{d}ipw2x00.LICENSE` remains)."]
        if fw.get("stock_bundle"):
            # Counted in all four stock bundles: 155 .fw files, plus the installer's
            # catalog, which is the 156th entry in that directory and not firmware. The
            # same set on Debian and Slackware (which spells the directory lib/firmware).
            lines += [f"- `{STOCK_FIRMWARE}` also holds the Broadcom b43 firmware Slax's build extracted "
                      f"from Broadcom's driver: 155 files in `{d}b43/`, beside the installer's "
                      "catalog, and no license text came with them."]
        lines.append("")
    lines += ["| | components |", "|---|---|"]
    for c in CLASSES:
        lines.append(f"| {c} | {s.get(c, 0)} |")
    lines += ["", "## Where each upstream publishes its source", "",
              f"- **Slax**, as its author built it: <{SLAX_SOURCE}> and the repositories it names."]
    debs, other = {}, {}
    for comp in doc["components"]:
        for p in comp.get("packages") or []:
            if p.get("archive") in (None, "debian") and p.get("source") and p.get("source_version"):
                debs[(p["source"], p["source_version"])] = p["source_published_at"]
            elif p.get("archive") not in (None, "debian", "slackware"):
                other[(p.get("package"), p.get("version"), p["archive"])] = p.get("source_published_at")
    if debs:
        lines.append(f"- **Debian source packages** ({len(debs)}):")
        for (src, ver), url in sorted(debs.items()):
            lines.append(f"  - `{src}` `{ver}` — <{url}>")
    slack: dict = {}
    for comp in doc["components"]:
        for p in comp.get("packages") or []:
            if p.get("archive") == "slackware":
                ups = p.get("source_published_at")
                slack.setdefault(tuple(ups) if isinstance(ups, list) else (ups,), []).append(p["package"])
    for ups, names in sorted(slack.items(), key=lambda kv: str(kv[0])):
        lines.append(f"- **Slackware packages** ({len(names)}), source "
                     + (", ".join(f"<{u}>" for u in ups if u) or "not named") + ": "
                     + ", ".join(f"`{n}`" for n in sorted(names)))
    for h in doc.get("host_inputs") or []:
        hp = h["host_package"]
        lines.append(f"- `{h['input']}`, copied by `{h['recipe']}` from the build host's "
                     f"`{hp.get('package')}` `{hp.get('version') or hp.get('source_version')}` "
                     f"— <{h['published_at']}>")
    for (name, ver, archive), up in sorted(other.items()):
        ups = up if isinstance(up, list) else [up] if up else []
        lines.append(f"- `{name}` `{ver}`, from `{archive}` — "
                     + (", ".join(f"<{u}>" for u in ups) or "no upstream source named"))
    for comp in doc["components"]:
        for part in comp.get("parts") or []:
            for lib in part.get("linked") or []:
                lines.append(f"- `{lib['name']}` `{lib.get('version')}` ({lib.get('license')}), "
                             f"statically linked into `{part.get('member')}` — "
                             f"<{lib.get('source_published_at')}>")
        if comp["class"] == "prebuilt":
            lines.append(f"- `{comp['path']}` — {comp.get('what') or comp.get('source')}"
                         + (f" — source: {comp.get('upstream_source')}"
                            if comp.get("upstream_source") else ""))
        if comp.get("fetched"):
            ups = {str(f.get("upstream_source")) for f in comp["fetched"]}
            lines.append(f"- `{comp['path']}` — {len(comp['fetched'])} fetched file(s); "
                         f"source: {', '.join(sorted(ups))}")
    built = [c for c in doc["components"] if c["class"] == "built"] + [
        dict(p, path=f"{c['path']}:{p['member']}") for c in doc["components"]
        for p in c.get("parts") or [] if p.get("class") == "built"]
    if built:
        lines += ["", "## Built here", ""]
        for b in built:
            what = b.get("what") or f"`{b.get('member')}`"
            if b.get("source_package"):
                sp = b["source_package"]
                lines.append(f"- `{b['path']}` — {what}, from source package `{sp.get('source')}` "
                             f"`{sp.get('version')}` — <{sp.get('published_at')}>")
            for src in b.get("sources") or []:
                lines.append(f"- `{b['path']}` — built from <{src['url']}> (sha256 `{src['sha256']}`)")
            if (b.get("config") or {}).get("file"):
                lines.append(f"  - build configuration `{b['config']['file']}`")
    ours = [c for c in doc["components"] if c["class"] == "ours"]
    if ours:
        kit = doc.get("kitchen") or {}
        lines += ["", "## Written by slax-kitchen and its recipes", "",
                  f"In the project source archive at `{kit.get('describe')}`, with its submodules.", ""]
        for c in ours:
            lines.append(f"- `{c['path']}` — {c.get('by')}")
    if doc.get("assets"):
        lines += ["", "## Source attached with this image", ""]
        for asset in doc["assets"]:
            lines.append(f"- `{asset['file']}` — {asset['what']} (sha256 `{asset['sha256']}`)")
    if doc["unresolved"]:
        lines += ["", "## Unresolved", ""]
        for u in doc["unresolved"]:
            lines.append(f"- `{u['path']}` — {u['reason']}")
    if doc["not_redistributable"]:
        lines += ["", "## Not redistributable", ""]
        for n in doc["not_redistributable"]:
            lines.append(f"- `{n['recipe']}` — {n['why']}")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ fetch ---------

UA = "slax-kitchen sources (+https://github.com/Fullaxx/slax-kitchen)"


def _get(url: str, dest: str) -> None:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=300) as r, open(dest + ".part", "wb") as f:
        shutil.copyfileobj(r, f)
    os.replace(dest + ".part", dest)


def _sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for c in iter(lambda: f.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


def project_tarball(root: str, state: dict, name: str, dest_dir: str) -> str:
    """`git archive` of the recorded commit, with every recorded submodule inside it, as a
    deterministic .tar.gz. GitHub's automatic source archives omit submodules."""
    commit = state["commit"]
    out = os.path.join(dest_dir, f"{name}-{commit[:12]}-source.tar.gz")
    with tempfile.TemporaryDirectory() as tmp:
        main = os.path.join(tmp, "main.tar")
        subprocess.run(["git", "-C", root, "archive", "--format=tar", f"--prefix={name}/",
                        "-o", main, commit], check=True)
        with tarfile.open(main, "a") as tar:
            for path, sha in sorted((state.get("submodules") or {}).items()):
                part = os.path.join(tmp, "sub.tar")
                subprocess.run(["git", "-C", os.path.join(root, path), "archive", "--format=tar",
                                f"--prefix={name}/{path}/", "-o", part, sha], check=True)
                with tarfile.open(part) as sub:
                    for m in sub.getmembers():
                        tar.addfile(m, sub.extractfile(m) if m.isfile() else None)
            info = tarfile.TarInfo(f"{name}/SUBMODULES.txt")
            body = "".join(f"{sha} {path}\n" for path, sha in
                           sorted((state.get("submodules") or {}).items())).encode()
            info.size, info.mtime = len(body), 0
            import io
            tar.addfile(info, io.BytesIO(body))
        with open(main, "rb") as src, open(out, "wb") as raw:
            with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as gz:
                shutil.copyfileobj(src, gz)
    return out


def fetch_debian_style_source(source: str, version: str, builder: dict, dest: str) -> list[str]:
    """A source package at an exact version: apt-get source when the host has deb-src,
    else Launchpad (Ubuntu builder) or snapshot.debian.org (Debian builder), every file
    verified against the .dsc's Checksums-Sha256."""
    os.makedirs(dest, exist_ok=True)
    before = set(os.listdir(dest))
    if shutil.which("apt-get"):
        r = subprocess.run(["apt-get", "source", "--download-only", f"{source}={version}"],
                           cwd=dest, capture_output=True, text=True)
        new = sorted(set(os.listdir(dest)) - before)
        if r.returncode == 0 and any(n.endswith(".dsc") for n in new):
            return new
    noepoch = version.split(":", 1)[-1]
    dsc_name = f"{source}_{noepoch}.dsc"
    if builder.get("id") == "ubuntu":
        base = (f"https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/"
                f"{source}/{urllib.parse.quote(version, safe='')}/")
        urls = {dsc_name: base + dsc_name}
        _get(urls[dsc_name], os.path.join(dest, dsc_name))
        text = open(os.path.join(dest, dsc_name), errors="replace").read()
        m = re.search(r"^Checksums-Sha256:\n((?:[ \t].+\n?)+)", text, re.M)
        if not m:
            raise RuntimeError(f"{dsc_name}: no Checksums-Sha256")
        got = [dsc_name]
        for ln in m.group(1).strip().splitlines():
            sha, _size, name = ln.split()
            path = os.path.join(dest, name)
            _get(base + name, path)
            if _sha256(path) != sha:
                raise RuntimeError(f"{name}: sha256 does not match {dsc_name}")
            got.append(name)
        return got
    info = json.load(urllib.request.urlopen(urllib.request.Request(
        f"https://snapshot.debian.org/mr/package/{source}/{urllib.parse.quote(version, safe='')}"
        "/srcfiles?fileinfo=1", headers={"User-Agent": UA}), timeout=120))
    got = []
    for h, entries in (info.get("fileinfo") or {}).items():
        name = entries[0]["name"]
        path = os.path.join(dest, name)
        _get(f"https://snapshot.debian.org/file/{h}", path)
        if hashlib.sha1(open(path, "rb").read()).hexdigest() != h:
            raise RuntimeError(f"{name}: sha1 does not match snapshot's hash")
        got.append(name)
    return got


def fetch_built(doc: dict, prov: dict, dest: str) -> list[dict]:
    """Gather the source of everything classed `built`, and the project tree(s)."""
    os.makedirs(dest, exist_ok=True)
    assets = []
    kitchen = prov.get("kitchen") or {}
    if kitchen.get("commit"):
        out = project_tarball(REPO, kitchen, "slax-kitchen", dest)
        assets.append({"what": "slax-kitchen at the recorded commit, with submodules",
                       "for": "(kitchen)", "file": os.path.basename(out), "sha256": _sha256(out)})
    project = prov.get("project")
    root = provenance.project_root()
    if project and project.get("commit") and root:
        out = project_tarball(root, project, os.path.basename(os.path.abspath(root)), dest)
        assets.append({"what": "the project at the recorded commit, with submodules",
                       "for": "(project)", "file": os.path.basename(out), "sha256": _sha256(out)})
    builder = doc.get("builder") or {}
    for comp in doc["components"]:
        if comp["class"] == "built" and comp.get("source_package"):
            sp = comp["source_package"]
            sub = os.path.join(dest, f"{sp['source']}_{sp['version'].split(':', 1)[-1]}")
            for name in fetch_debian_style_source(sp["source"], sp["version"], builder, sub):
                p = os.path.join(sub, name)
                assets.append({"what": f"source of {comp['what']}", "for": comp["path"],
                               "file": os.path.relpath(p, dest), "sha256": _sha256(p)})
        for part in comp.get("parts") or []:
            if part.get("class") != "built":
                continue
            for src in part.get("sources") or []:
                name = os.path.basename(urllib.parse.urlsplit(src["url"]).path)
                p = os.path.join(dest, name)
                _get(src["url"], p)
                if _sha256(p) != src["sha256"]:
                    raise RuntimeError(f"{name}: sha256 does not match the build claim")
                assets.append({"what": f"source of {part['member']}", "file": name,
                               "for": f"{comp['path']}:{part['member']}", "sha256": src["sha256"]})
            cfg = part.get("config") or {}
            if cfg.get("file"):
                # Beside the binary the build used, found from its recorded location; the
                # kitchen's build/ is where tools/build-busybox.sh writes by default.
                roots = {"kitchen": REPO, "project": provenance.project_root()}
                loc = part.get("location") or {}
                candidates = [os.path.join(REPO, "build", cfg["file"])]
                if roots.get(loc.get("root")):
                    candidates.insert(0, os.path.join(roots[loc["root"]],
                                                      os.path.dirname(loc["path"]), cfg["file"]))
                local = next((c for c in candidates
                              if os.path.isfile(c) and _sha256(c) == cfg.get("sha256")), None)
                if not local:
                    raise RuntimeError(f"{cfg['file']}: not found beside the build, or it is "
                                       "not the config the build claim names")
                shutil.copy2(local, os.path.join(dest, cfg["file"]))
                assets.append({"what": f"build configuration of {part['member']}",
                               "for": f"{comp['path']}:{part['member']}",
                               "file": cfg["file"], "sha256": cfg["sha256"]})
    return assets


# ------------------------------------------------------------------ main ----------

def check_local_inputs(prov: dict) -> None:
    """Mark every recorded local input `in_archive`: does the recorded commit of the
    checkout it sat in hold exactly this content? Git answers without a checkout of that
    commit, so this works from any clone that has it."""
    roots = {"kitchen": REPO, "project": provenance.project_root()}
    commits = {"kitchen": (prov.get("kitchen") or {}).get("commit"),
               "project": (prov.get("project") or {}).get("commit")}
    for r in prov.get("recipes") or []:
        inputs = [r["recipe_file"]] if r.get("recipe_file") else []
        inputs += [li for st in r.get("steps") or [] for li in st.get("local_inputs") or []]
        for li in inputs:
            if li.get("outside"):
                continue
            root, commit = roots.get(li.get("root")), commits.get(li.get("root"))
            if not root or not commit:
                li["in_archive"] = False
                li["why"] = ("set PROJECT_ROOT to the project checkout" if li.get("root") == "project"
                             else "no commit recorded")
                continue
            li["in_archive"] = provenance.git_digest(root, commit, li["path"], li["kind"]) == li["digest"]


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="kitchen sources", description=__doc__.split("\n\n")[0])
    ap.add_argument("iso")
    ap.add_argument("--provenance", help="default: <iso>.provenance.json")
    ap.add_argument("--json", help="write the machine-readable manifest here")
    ap.add_argument("--markdown", help="write the human-readable manifest here")
    ap.add_argument("--fetch", metavar="DIR", help="gather the source of what was built here")
    ap.add_argument("--allow-dirty", action="store_true",
                    help="accept uncommitted work: an image built from a kitchen tree with "
                         "uncommitted changes, and recipe files and copied-in inputs the "
                         "recorded commit does not hold (untracked or gitignored ones "
                         "too), which are then classed as if it did")
    ap.add_argument("--strict", action="store_true",
                    help="a download with no upstream_source, or none pinned by sha256, "
                         "is unresolved rather than a warning")
    a = ap.parse_args(argv[1:])
    # xorriso lists the image. git on every run, not only --fetch: every local input is
    # looked up at its recorded commit (provenance.git_digest), which the first version of
    # this check missed -- --fetch was where git was visible, not where it was first used.
    need.require(["xorriso", "git"], "kitchen sources")

    prov_path = a.provenance or a.iso + ".provenance.json"
    if not os.path.isfile(prov_path):
        print(f"kitchen sources: no provenance at {prov_path}\n"
              f"  `kitchen pack` writes it beside the ISO; rebuild with this kitchen.",
              file=sys.stderr)
        return 2
    prov = json.load(open(prov_path))
    import yaml
    sources_yaml = yaml.safe_load(open(os.path.join(REPO, "compat", "sources.yaml"))) or {}
    target, info = base_target(prov, sources_yaml)
    stock = stock_index(target, os.path.join(REPO, "docs", "30-inventory", "manifests"))
    # A LISTING THAT FAILED IS NOT AN IMAGE WITH NOTHING IN IT. classify() accounts for the
    # files it is given, so an empty listing -- xorriso 1.5.6 exits 0 on a file it cannot
    # read as an ISO -- used to come out "unresolved 0" and pass, --strict included: a
    # pass for an image nobody had examined. diff._entries() now refuses such a listing.
    import diff
    try:
        files = iso_files(a.iso)
        check_local_inputs(prov)
        # Unpack the initramfs only when there is something to learn: it is not the stock
        # one (an untouched initrfs.img is answered by its own sha256) and this target has a
        # manifest to compare it against. Otherwise the xz is work whose result is unusable.
        irfs = files.get("slax/boot/initrfs.img")
        members = (initramfs_members(a.iso)
                   if irfs and stock["initramfs"]
                   and stock["files"].get("slax/boot/initrfs.img") != irfs else None)
    except diff.ListingError as e:
        print(f"kitchen sources: {e} -- so nothing in it can be accounted for", file=sys.stderr)
        return 2
    doc = classify(files, stock, prov, target, info, a.allow_dirty, a.strict,
                   initramfs=members)
    if ((prov.get("pack") or {}).get("iso") or {}).get("sha256") not in (None, _sha256(a.iso)):
        doc["unresolved"].append({"path": "(image)", "reason": "the ISO's sha256 is not the one "
                                  "its provenance records -- it changed after pack"})
        doc["summary"]["unresolved"] = len(doc["unresolved"])

    rc = 1 if doc["unresolved"] else 0
    if a.fetch and not doc["unresolved"]:
        try:
            doc["assets"] = fetch_built(doc, prov, a.fetch)
        except (OSError, RuntimeError, subprocess.CalledProcessError, ValueError) as e:
            doc["unresolved"].append({"path": "(fetch)", "reason": str(e)})
            doc["summary"]["unresolved"] = len(doc["unresolved"])
            rc = 1
    if a.json:
        with open(a.json, "w") as f:
            json.dump(doc, f, indent=1, sort_keys=True)
            f.write("\n")
    if a.markdown:
        open(a.markdown, "w").write(markdown(doc))

    s = doc["summary"]
    print(f"sources  {doc['image'].get('name')}  (base {target or 'unknown'})")
    print("  " + "  ".join(f"{c} {s[c]}" for c in CLASSES))
    for w in doc["warnings"]:
        print(f"  warning: {w}")
    for n in doc["not_redistributable"]:
        print(f"  not redistributable: {n['recipe']} -- {n['why']}")
    for u in doc["unresolved"]:
        print(f"  UNRESOLVED {u['path']}: {u['reason']}")
    for asset in doc.get("assets") or []:
        print(f"  fetched  {asset['file']}")
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv))
