#!/usr/bin/env python3
"""Validate recipes, profiles and fingerprints against their JSON Schemas.

Called by the 40-schema commit gate and by `kitchen apply` before a recipe runs --
a malformed recipe should fail at the gate, not halfway through mutating a work tree.
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCHEMA_FOR_KIND = {
    "Recipe": "recipe.schema.json",
    "Profile": "profile.schema.json",
    "Sources": "sources.schema.json",
    "UpstreamBaseline": "upstream-baseline.schema.json",
}


def _subst(obj, vars_: dict):
    """Same {{name}} substitution apply.py performs, so validation sees what will run.

    Unknown names are left intact rather than raising: apply.py is the place that
    reports them, with the step number.
    """
    if isinstance(obj, str):
        return re.sub(r"\{\{([^}]+)\}\}",
                      lambda m: vars_.get(m.group(1).strip(), m.group(0)), obj)
    if isinstance(obj, dict):
        return {k: _subst(v, vars_) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_subst(v, vars_) for v in obj]
    return obj


def recipe_name(ref: str) -> str:
    """The name a recipe reference stands for: its filename stem.

    A reference is a bare name or a path to the file, and a recipe's metadata.name must
    equal its filename stem (checked below), so the stem IS the name either way. Names
    cannot contain a dot (schema/recipe.schema.json), so the first dot from the right is
    always the extension's.

    Stated once, because the two ends of a profile's per-recipe vars used to compute it
    differently: read_profile_recipes stored an override under the entry as written, and
    apply's main() looked it up by stem, so a path entry's vars were dropped in silence (#46).
    """
    return os.path.basename(ref).rsplit(".", 1)[0]


def validate_file(path: str, overrides: dict | None = None) -> list[str]:
    """Return a list of human-readable problems; empty means valid.

    `overrides` are per-build values for the recipe's `vars:`, from a profile. They have
    to reach HERE rather than being applied afterwards: this function resolves vars
    before schema-checking, so validating without them would check the recipe's default
    and let an override through.
    """
    import yaml
    try:
        import jsonschema
    except ImportError:
        return ["jsonschema not installed (pip install jsonschema)"]

    try:
        doc = yaml.safe_load(open(path))
    except yaml.YAMLError as e:
        return [f"not valid YAML: {e}"]
    if not isinstance(doc, dict):
        return ["top level must be a mapping"]

    # Validate the RESOLVED document. A recipe's vars are substituted into step strings
    # at apply time, so validating the raw form would reject a perfectly good
    # bundle: "{{bundle}}" against the NN-name pattern the verb actually requires.
    declared = doc.get("vars") if isinstance(doc.get("vars"), dict) else {}
    if overrides:
        unknown = [k for k in overrides if k not in declared]
        if unknown:
            # Silently ignoring an override is how `network: true` sat in a docstring
            # for months doing nothing. Name what IS available instead.
            return [f"overrides a var this recipe does not declare: "
                    f"{', '.join(sorted(unknown))} "
                    f"(declared: {', '.join(sorted(declared)) or 'none'})"]
        declared = {**declared, **overrides}
    if declared:
        doc = _subst(doc, {k: str(v) for k, v in declared.items()})

    kind = doc.get("kind")
    if kind == "Fingerprint":
        # Generated by lib/fingerprint.py, never hand-written, so there is no user error
        # to catch -- but there IS generator error, and these four files are the ground
        # truth `kitchen probe` compares against. Structural validation is still owed.
        return []
    if kind not in SCHEMA_FOR_KIND:
        return [f"unknown kind {kind!r} (want one of {sorted(SCHEMA_FOR_KIND)})"]

    schema_path = os.path.join(ROOT, "schema", SCHEMA_FOR_KIND[kind])
    if not os.path.isfile(schema_path):
        return [f"schema missing: {schema_path}"]
    import json
    schema = json.load(open(schema_path))

    problems = []
    v = jsonschema.Draft202012Validator(schema)
    errs = sorted(v.iter_errors(doc), key=lambda e: list(e.path))
    # `unevaluatedProperties` reports a step's OWN fields as unexpected whenever the
    # verb's if/then branch failed for some other reason -- so one bad bundle name
    # produced "('bundle', 'packages') were unexpected", which is both alarming and
    # untrue. When a more specific error exists for the same step, that one is the
    # answer; the unevaluated complaint is a consequence of it.
    specific = [tuple(e.path) for e in errs if e.validator != "unevaluatedProperties"]
    for err in errs:
        here = tuple(err.path)
        if err.validator == "unevaluatedProperties" and any(
                other[:len(here)] == here for other in specific):
            continue
        where = "/".join(str(p) for p in err.path) or "(root)"
        problems.append(f"{where}: {err.message}")

    # Cross-checks the schema cannot express.
    if kind == "Sources":
        # A layout referencing a field no target defines would only fail at download
        # time, in CI, after a long apt install.
        import string
        fields = {f for _, f, _, _ in string.Formatter().parse(
            " ".join(m["layout"] for m in doc.get("mirrors", []))) if f}
        for name, spec in (doc.get("targets") or {}).items():
            missing = fields - set(spec)
            if missing:
                problems.append(f"target {name} has no {', '.join(sorted(missing))} "
                                "but a mirror layout references it")
    if kind == "Recipe":
        # A recipe that removes or renumbers a bundle does nothing else. Mixing the two
        # hides a deletion inside an addition, and the deletion then dictates where the
        # recipe may sit: all-browsers removed 05-chromium as its first step, so
        # check_plan_order refused any plan that listed it after another bundle had been
        # built -- a constraint that read as being about browsers and was about removal.
        # Kept apart, the removal recipe goes first and the additive ones compose freely.
        verbs = [st.get("verb") for st in doc.get("steps") or [] if isinstance(st, dict)]
        cuts = [v for v in verbs if v in ("bundle.remove", "bundle.renumber")]
        if cuts and len(cuts) != len(verbs):
            # A step with no `verb` at all is a schema error, already reported above -- but
            # this cross-check still runs, and None must not reach sorted()/join().
            others = sorted({v or "a step with no verb" for v in verbs
                             if v not in ("bundle.remove", "bundle.renumber")})
            problems.append(
                f"{cuts[0]} shares this recipe with {', '.join(others)}: a recipe that removes "
                f"or renumbers a bundle does nothing else. Put the removal in its own recipe -- "
                f"remove-bundle takes a `drop:` pattern -- and list that first; every other "
                f"recipe then composes in any order. See docs/40-workflow/composing-bundles.md.")
        stem = recipe_name(path)
        name = (doc.get("metadata") or {}).get("name")
        if name and name != stem:
            problems.append(
                f"metadata.name {name!r} does not match filename stem {stem!r} "
                "(recipes are referenced by name, so these must agree)")
    return problems


def main(argv: list[str]) -> int:
    # argparse, not a length check: `kitchen validate --help` used to reach the loop
    # below and die with a FileNotFoundError traceback for a file called "--help".
    import argparse
    ap = argparse.ArgumentParser(
        prog="kitchen validate",
        description="check a recipe, profile, sources or fingerprint file "
                    "against its JSON Schema")
    ap.add_argument("files", nargs="+", metavar="FILE.yaml")
    args = ap.parse_args(argv[1:])
    rc = 0
    for path in args.files:
        problems = validate_file(path)
        if problems:
            rc = 1
            for p in problems:
                print(f"{path}: {p}", file=sys.stderr)
    return rc


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
